### ISSUE TITLE
configure "texture" editor properly

### ISSUE THREAD

**Issue by nathandunn** [InSilicoLabs/texture#1]
- [x] render full
- [x] make readonly mostly
- [x] edit links only

**Comment by nathandunn** [comment]
currently links look like:

    <ext-link id="{some-uuid}">some phrase</ext-link>

**Comment by nickstiffler** [comment]
I am able to set the componenet attribitute "contenteditable=false", but if you try to edit the document, it changes back to contenteditable=true.

**Comment by nathandunn** [comment]
Weird.  You may need to do something other than the “author” package to make it work properly.   Not sure.

**Comment by nickstiffler** [comment]
I figured how to make it read-only, although we may still want to create our own custom component.

**Comment by nathandunn** [comment]
Yeah, we'l have to do a custom component for the link.  But this works correctly.
