### ISSUE TITLE
create-fix custom edit link

### ISSUE THREAD

**Issue by nathandunn** [InSilicoLabs/texture#5]
Need to create the proper custom-edit link or make it work properly. 

Should:

- [ ] markup properly 
- [ ] store the link amrkup.
- [ ] get data from the lexica
- [ ] export the proper "final" ID

**Comment by nathandunn** [comment]
So the way to do this is in "texture", by creating / fixing the "link" package.  ext-link is the proper jats XML.  I'm a bit confused with how the link resolves to an ID, but hopefully we can figure that out.

**Comment by nathandunn** [comment]
These were notes from #78, feel free to remove, etc. as you feel fit.

- [ ] write output with an ID for the lexicon term
- [ ] write output that links a server to redirect to the term lookup before redirecting to the page (e.g., gene page at ZFIN)
- [ ] write server to read these
- [ ] We need to verify that we have an "id", the proper link location, the term, the external source, etc.

**Comment by nickstiffler** [comment]
I think I am close. I added extLinkId from texture to markup so it can retrieve the correct markup. Look at EditExtLinkTool.js. It uses a request to retrieve the markup, but I wasn't able to get the lexica sources into the select.

**Comment by nathandunn** [comment]
Hmm.  The model is a bit tricky.    Sometimes you have to do an explicit join with the KeyWord request.   This is what I did when I called getLinkedTerms.  Its should be an almost identical call:

https://github.com/InSilicoLabs/dmc-grails/blob/master/server/grails-app/controllers/com/insilico/dmc/PublicationController.groovy#L183

This ends up retrieving lexicon source.  In this case there is just one, but it will retrieve multiple, as well:

<img width="337" alt="screen shot 2017-08-03 at 11 14 12 pm" src="https://user-images.githubusercontent.com/751274/28956478-050f9700-78a2-11e7-9dc8-dec40e398f38.png">

**Comment by nickstiffler** [comment]
The problem I am having is it is making an asynchronous request for the data, but the widget is already rendered by the time the data arrives and put in the widget. I either need a way to have it wait until the data arrives before rendering, or to force it to rerender after it arrives.

**Comment by nathandunn** [comment]
Just brainstorming (I haven’t looked in depth with the API, but the problem is all-to-familiar):

1 - have render method be called as part of the data request callback
2 - have data callback call the render method again (a bit jarring, but useful)
3 - set a state function that only calls once the data is called again
4 - have the callback make its own render calls.

I’m not sure how hard it is to over-ride the render / callback function to do any of that.

**Comment by nathandunn** [comment]
@nickstiffler  Is this one done, or just part of it?   Not a big deal, just trying to track.  I think we have what we need for the demo.  The only difference is that there is a markup.finalLexicon  selected it should reflect hat.

**Comment by nickstiffler** [comment]
I the pieces are in place, I just wasn't sure what needs to be displayed and edited in the texture side vs. the angular side. I can work on having it update the finalLexicon though.

**Comment by nathandunn** [comment]
I think this is done
